module.exports = {
  DJTestPanel: {
    enable: true,
    panels: [['panel-default', { enable: true, entry: 'app.tsx' }]],
  },
  AirPurifier: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  FiveRoadHub: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  FiveRoadLight: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  Locator: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  Socket: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  MultiSwitch: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  VideoCamera: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  Fan: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  RuyingMultiSwitch: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  WisdomControl: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  KugouMusic: {
    enable: false,
    panels: [['panel-default', { enable: false, entry: 'app.tsx' }]],
  },
  ElectricFan: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  WhiteLamp: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  AirConditioner: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  AirCleaner: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  BloodPressureMeter: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  BodyScales: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  BodySensor: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  DisinfectionCabinet: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ElectricCurtains: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  FivePlug: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  FiveStreetlights: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  FourStreetlights: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  FourSwitch: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ThreeSwitch: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  TwoSwitch: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  InsertKeyPower: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  IntelligentGateway: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  OneLamp: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  LaundryRack: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  MultifunctionAlarmHost: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  NewFan: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  Router: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ThreePlug: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  WallPlug: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ThreeStreetlights: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  WaterHeater: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  WaterPurifier: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  AudibleVisualAlarm: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  EmergencyButton: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ElectricOven: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  GasAlarm: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  Heater: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  Humidifier: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ImmersionSensor: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  MagneticDoor: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  PetFeedingDevice: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  SmartRope: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  SmokeAlarm: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  SwitchOne: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  TemperatureHumiditySensor: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  Thermostat: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  DimmerSwitch: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ElectricityStatsReceptacle: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  AromatherapyMachine: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  },
  ElectricCar: {
    enable: false,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: false, entry: 'app.tsx' }],
      ['panel-dark', { enable: false, entry: 'app.tsx' }],
      ['panel-colorful', { enable: false, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: false, entry: 'app.tsx' }],
      ['panel-morandi', { enable: false, entry: 'app.tsx' }],
    ],
  }
};
